# Runtime
--js-runtime node

# Prueba segura
--simulate

# Seleccionar el mejor audio
--format "ba[acodec^=mp4a]/ba"

# Conversión final
--extract-audio
--audio-format mp3
--audio-quality 0

# Salida
--output "downloads/audio/%(channel,uploader|Unknown channel)s/%(title).80s [%(id)s].%(ext)s"

# Recuperación
--continue
--part