# Runtime
--js-runtime node

# Best audio format
--format "ba[acodec^=mp4a]/ba"

# Secure test
--simulate

# Final conversion
--extract-audio
--audio-format mp3
--audio-quality 0

# Output
--output "downloads/audio/%(channel,uploader|Unknown channel)s/%(title).80s [%(id)s].%(ext)s"

# Recovery
--continue
--part