# Runtime
--js-runtime node

# Best video
--format "bv[height<=1080][vcodec^=avc1]+ba[acodec^=mp4a]/b[height<=1080]"

# Secure test
--simulate

# Output
--output "downloads/video/%(channel,uploader|Unknown channel)s/%(title).80s [%(id)s].%(ext)s"

# Final Container
--merge-output-format mp4

# Recovery
--continue
--part

# Abort
--abort-on-error